### ISSUE TITLE
can't update anymore

### ISSUE THREAD

**Issue by kosuodhmwa** [clamwin/clamwin-py#2]
![cw](https://user-images.githubusercontent.com/24782840/110608057-2456b980-818c-11eb-939c-8456bf92ce0a.JPG)

Thank you very much for your feedbacks...

**Comment by kosuodhmwa** [comment]
oh it was the wrong picture...

![cw2](https://user-images.githubusercontent.com/24782840/110608278-62ec7400-818c-11eb-8954-a64440f42f48.JPG)

**Comment by adamprato** [comment]
The issue is that clamav 0.99 is EOL as per a related problem posted here - https://forum.qnap.com/viewtopic.php?t=159990&p=782294#p782295
```
Re: [Open] TS-669 p Antivirus Failed to update virus definitions. Please try again later or update the definitions manua
Post by JoelEsler » Sun Mar 07, 2021 7:15 am

Hello. Joel from ClamAV here. It has become necessary to restrict wget based clients, so that’s why wget isn’t working. Freshclam may not be working because you’re running an old version of ClamAV. If you’re older than 0.100, then your version is EOL and ClamAV needs to be updated.
```
Another discussion on the clamwin forum here - http://forums.clamwin.com/viewtopic.php?t=5226

**Comment by kosuodhmwa** [comment]
But the version i use is that latest stable for download von ClamWin site:
http://www.clamwin.com/content/view/18/46/

I'm confused...?

**Comment by adamprato** [comment]
> But the version i use is that latest stable for download von ClamWin site:
> http://www.clamwin.com/content/view/18/46/

The latest stable version is already a year or so old. Please look at the links I found - ClamAV is denying the update access because the ClamAV bundled with ClamWin 0.99 is end-of-life.

In the meantime I installed immunet which is also free.

**Comment by kosuodhmwa** [comment]
Works, thank you very very much!!! :-)
