### ISSUE TITLE
Database update failing

### ISSUE THREAD

**Issue by lambic12** [clamwin/clamwin-py#3]
Hello,

For a few days I have these error message when I want to update the database :
ClamAV update process started at Mon Mar 15 12:19:38 2021
main.cld is up to date (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
WARNING: getpatch: Can't download daily-26096.cdiff from database.clamav.net

When I change the update server, the problem is the same.
I think it is because of the gap between the engine in Clamwin (0.99.4) and the last ClamAV version (0.103.0), I read somewhere that when the gap is more than 3 versions, the update is refused.
Is it possible to make a Clamwin version with an up-to-date engine ?

Thank you.

**Comment by lulol** [comment]
This is what I found.

> [**JoelEsler** _Sun Mar 07, 2021 7:15 am_](https://forum.qnap.com/viewtopic.php?f=345&t=159990#p782295)
>
> Hello. Joel from ClamAV here. It has become necessary to restrict wget based clients, so that’s why
> wget isn’t working. Freshclam may not be working because you’re running an old version of ClamAV. If you’re older than 0.100, then your version is EOL and ClamAV needs to be updated.

ClamWin 0.99.4 was last updated 3 years ago and so it seems that is too old and has been blocked.

But despite not having a readily available updated full package it seems that you can still use your old ClamWin GUI with the current clamav binaries downloaded separately as explained below.
 
> [**congoclash** _Posted: Fri Mar 12, 2021 1:53 pm_](http://forums.clamwin.com/viewtopic.php?p=21597#21597)
>
> Here's the easy way to fix this:
> 
> 1. Download the new clamAv engine v0.103.0 from https://oss.netfarm.it/clamav/
> If you choose the x64 package, you'll need MS Visual C++ 2019 installed (link on the same page)
> 2. Unzip it to a new folder of your choice
> 3. Open ClamWin and click the settings button
> 4. Go to the "file locations" tab
> 5. Edit the first 2 fields to point freshclam.exe and clamscan.exe to the new versions you downloaded
> 
> That's it, ClamWin is now operational.

EDIT:
The explanation is now in [ClamAV's blog](https://blog.clamav.net/2021/03/clamav-cvds-cdiffs-and-magic-behind.html).
The virus database has grown so big that in systems with less than 2GB of ram the update was failing and after 90 days the cdiffs are gone so freshclam then kept trying downloading the full cvd file that also failed. ClamAV's database was serving 9 Petabytes/month.

@sawyerit duplicate of clamwin/clamav-win32/issues/9

**Comment by sherpya** [comment]
we are working for a new release

**Comment by lulol** [comment]
Awesome! Thank you!

The new [0.103.2 release](https://clamwin.com/content/view/18/46/) seems to work fine out of the box, with WinXP running in a non-SSE2 enabled cpu (but with only 1GB ram the database will fail to load into memory). Also runs fine in Win8.1.
And in XP with virtualbox.

@sherpya
The download link in https://clamwin.com/content/view/251/1/ to https://clamwin.com/download redirects to <s>https://clamwin.com/https://clamwin.com/content/view/18/46//</s> which is malformed.

**Comment by sherpya** [comment]
@alexcherney

**Comment by alexcherney** [comment]
Fixed the link (invalid redirect). Thanks for letting me know

**Comment by lambic12** [comment]
Hello

I installed the new release of ClamWin, but since today I have a 403 
error when trying to update.

I contacted the ClamAV team and they said :

Your of ClamAV is not identifying itself correctly to the server. It must
contain a UUID.  Someone has modified the code for freshclam. This will be
blocked until the ClamWin maintainers correct and Unmodify the code

Your version*


Le 02/05/2021 à 19:23, Gianluigi Tiesi a écrit :

**Comment by lulol** [comment]
@lambic12 The new version 0.103.2.1 fixed the issue! :smile:

**Comment by Umeaboy** [comment]
Uuuuuhm. It doesn't work for me now and I'm using Clamwin in Windows 7. Yes, I know that Windows 7 is no longer being developed, but that doesn't mean that it stops working. I checked that I am running 0.103.2.1 and I am indeed running the same version. Any alternative to the database download url?
