### ISSUE TITLE
Error Code 0xc00012f on Windows Server 2012 Standard R2 x64 - why?

### ISSUE THREAD

**Issue by kosuodhmwa** [clamwin/clamwin-py#5]
Hi there...

Screenshot here:

![image](https://user-images.githubusercontent.com/24782840/140304673-1787c5f6-c7b2-4d74-80b3-acf262e721ec.png)

Thank you for your feedbacks.

With kind regards from Switzerland,
Jan

**Comment by kosuodhmwa** [comment]
???

**Comment by sherpya** [comment]
very strange, the error is "bad image", it is the only software that crashes with this error?

**Comment by kosuodhmwa** [comment]
Too late, i'm sry. i forgot what the problems was. The vm was re-installed now, but not because of that issue..
